# Generated by Django 4.1.3 on 2022-12-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_description_alter_car_door_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='door',
        ),
    ]
